### PR TITLE
GitHub Enterprise support

### LINKED ISSUE #21: Unable to find PR
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ tfsec --format=json .
+ echo 'tfsec violations were identified, running commenter...'
tfsec violations were identified, running commenter...
+ commenter
Starting the github commenter...
The commenter failed with the following error:
PR number [8] not found for DSC/github_actions

This is my workflow:

`
name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: [ self-hosted ]

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
`

Am I missing something?

### PR DESCRIPTION
**Pull request by kolomied**
Fixes #21 

Provide support for GitHub Enterprise environments (make use of GITHUB_API_URL env variable)

### CODE REVIEW

**Comment by heathsnow** [comment]
I just tried using this and I'm still getting the same error:

```
Starting the github commenter...
The commenter failed with the following error:
failed to create a new commenter. PR number [80] not found for <redacted repo>
```

**Comment by kathleenfrench** [comment]
Hey @kolomied - I created a fork in order to test your proposed changes on a Github Enterprise Server instance and can confirm it works 👍🏻.

I made [a few other unrelated changes](https://github.com/aquasecurity/tfsec-pr-commenter-action/compare/main...kathleenfrench:tfsec-pr-commenter-action:main) as it pertains to the issue at hand in that fork, which can be disregarded. The only code changes of importance are copied directly from this PR. 

I tested it while explicitly including an `env` property on the action for `GITHUB_API_URL`, but that shouldn't be necessary as that is a [default environment variable](https://docs.github.com/en/enterprise-server@3.5/actions/learn-github-actions/environment-variables) included in the PR context.

Please let me know if I can provide any more information!

**Comment by adcharre** [comment]
@owenrumney any chance you can merge this PR, we'd really like to be able to run this on our GitHub Enterprise server without forking it internal to fix this?

**Comment by Burim-Bilali** [comment]
@owenrumney can we get this merged please

**Comment by tbowman01** [comment]
Hi, Can we please review this PR?  Or get an expected time to review?
@liamg @owenrumney

**Comment by dschunack** [comment]
Hey @owenrumney @marcofranssen @liamg ,

any progress on this?

**Comment by marcofranssen** [comment]
I can't help here, not a maintainer.

**Comment by owenrumney** [comment]
@liamg and I are no longer maintainers I'm afraid.

I'd suggest the tfsec channel in the aqua slack channel to progress 

Good luck

**Review by giorod3 — APPROVED** [review]

**Comment by giorod3** [comment]
@kolomied I will be cutting a new release after a couple of open PR's are aligned. the new release will be v1.4.0

**Comment by dschunack** [comment]
Hi @giorod3 ,

Approximately when will it be released? We're waiting too.

**Comment by dschunack** [comment]
Hi @giorod3,

Any update ?

**Pull request merged**
